backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
# These lines should *not* be indented
media_folder: "static/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/uploads


# collections for blogs
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Display name in the UI
    folder: "exampleSite/content/english/blog" # Path to the folder where blog posts are stored
    create: true # Allow users to create new documents
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # Fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" } # Ensure the body is included
